import './js/gallery';
import './js/review-slider';
import './js/mobile-menu';
import './js/arrow-toggle';
import './js/modal';
import './js/modal_buy';
import './js/modal_ingridient';
import './js/modal_location';
import './js/modal_made';
